pipeline {
    agent {
        docker {
            image 'maven:3.9.0'
            args '-v /root/.m2:/root/.m2'
        }
    }
    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/aslamafif29/simple-java-maven-app.git'
            }
        }
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                // Verifikasi file dan izin eksekusi
                sh 'ls -l ./jenkins/scripts/'  // Verifikasi file dan izin eksekusi
                sh 'chmod +x ./jenkins/scripts/test.sh'  // Berikan izin eksekusi pada script
                sh './jenkins/scripts/test.sh'  // Jalankan script setelah diubah izin
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
